name: goocommerce
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.5 <3.0.0'

dependencies: 
  cupertino_icons: 1.0.5
  get: 4.6.5
  flutter_screenutil: ^5.3.1
  carousel_slider: ^4.0.0
  intro_slider: ^4.2.0
  introduction_screen: ^3.0.2
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  rflutter_alert: ^2.0.4
  loading_indicator: ^3.1.0
  load: ^1.0.0
  lottie: ^2.2.0
  flutter_svg: ^1.1.5
  jwt_decoder: ^2.0.1
  flutter_dotenv: ^5.0.2
  pin_code_fields: ^7.4.0
  image_picker: ^0.8.5+3
  flutter_svg_provider: ^1.0.3
  contained_tab_bar_view: ^0.8.0
  dropdown_button2: 2.1.2
  intl: ^0.17.0
  datetime_picker_formfield: ^2.0.1
  flutter_keyboard_visibility: ^5.3.0
  path_provider: ^2.0.11
  http: ^0.13.5
  pull_to_refresh: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  rename: ^2.0.1
  flutter_image_compress: ^1.1.3
  image: ^3.2.2
  flutter_native_image: ^0.0.6+1
  modal_bottom_sheet: ^3.0.0-pre
  uuid: ^3.0.6
  animated_text_kit: ^4.2.2
  json_annotation: 4.8.1
  flutter_native_splash: ^2.2.14
  google_fonts: ^4.0.3
  flutter_easyloading: 3.0.5
  appbar_animated: 0.0.3
  smooth_page_indicator: 1.1.0
  sliding_up_panel: 2.0.0+1
  animated_widgets: 1.1.0
  validatorless: 1.2.3
  freezed_annotation: 2.2.0
  build_runner: 2.3.3
  json_serializable: 6.6.1
  freezed: 2.3.2
  flutter_secure_storage: 8.0.0
  firebase_messaging: 14.6.1
  firebase_core: 2.13.0
  shimmer: 2.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/animations/
    - assets/svg/
    - assets/json/
    - .env
  uses-material-design: true

